name: core_picker
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"
  # ">=2.18.6 <3.0.0"

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  talker: ^3.1.1
  talker_dio_logger: ^2.3.0
  equatable: ^2.0.5
  freezed: ^2.3.0
  retrofit: ^4.0.1
  animations: ^2.0.7
  keyboard_dismisser: ^3.0.0
  camera: ^0.10.5+2
  permission_handler: ^10.2.0
  photo_manager: ^2.6.0
  fancy_shimmer_image: ^2.0.2
  device_info_plus: ^9.0.2
  video_thumbnail: ^0.5.3
  video_player: ^2.6.1
  lottie: ^2.3.2
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  file_picker: ^5.3.0
  draggable_scrollbar: ^0.1.0
  dio: ^5.0.2

  location:
    git:
      url: https://github.com/781flyingdutchman/flutterlocation.git
      ref: V4
      path: packages/location
  vif_previewer:
    path: ../previewer_package
  loader_overlay: ^2.3.2

dependency_overrides:
  build_runner: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  assets_gen: ^1.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
assets_gen:
  output: core/gens/assets.dart
  gen_package_path: true

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
