// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 10.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'core_picker';

  static const String assets_icons_135726_map_marker_json = 'assets/icons/135726-map-marker.json';
  static const String core_picker$assets_icons_135726_map_marker_json = 'packages/core_picker/assets/icons/135726-map-marker.json';

  static const String assets_icons_20431_cloud_storage_json = 'assets/icons/20431-cloud-storage.json';
  static const String core_picker$assets_icons_20431_cloud_storage_json = 'packages/core_picker/assets/icons/20431-cloud-storage.json';

  static const String assets_icons_20432_client_gallery_json = 'assets/icons/20432-client-gallery.json';
  static const String core_picker$assets_icons_20432_client_gallery_json = 'packages/core_picker/assets/icons/20432-client-gallery.json';

  static const String assets_icons_33518_paper_file_and_document_animations_json = 'assets/icons/33518-paper-file-and-document-animations.json';
  static const String core_picker$assets_icons_33518_paper_file_and_document_animations_json = 'packages/core_picker/assets/icons/33518-paper-file-and-document-animations.json';

  static const String assets_icons_63405_camera_json = 'assets/icons/63405-camera.json';
  static const String core_picker$assets_icons_63405_camera_json = 'packages/core_picker/assets/icons/63405-camera.json';

  static const String assets_icons_66746_music_json = 'assets/icons/66746-music.json';
  static const String core_picker$assets_icons_66746_music_json = 'packages/core_picker/assets/icons/66746-music.json';

  static const String assets_icons_93832_location_icon_json = 'assets/icons/93832-location-icon.json';
  static const String core_picker$assets_icons_93832_location_icon_json = 'packages/core_picker/assets/icons/93832-location-icon.json';

  static const String assets_icons_94217_check_right_json = 'assets/icons/94217-check-right.json';
  static const String core_picker$assets_icons_94217_check_right_json = 'packages/core_picker/assets/icons/94217-check-right.json';

  static const String assets_icons_97331_gallery_upload_json = 'assets/icons/97331-gallery-upload.json';
  static const String core_picker$assets_icons_97331_gallery_upload_json = 'packages/core_picker/assets/icons/97331-gallery-upload.json';

  static const String assets_icons_97425_mapa_json = 'assets/icons/97425-mapa.json';
  static const String core_picker$assets_icons_97425_mapa_json = 'packages/core_picker/assets/icons/97425-mapa.json';
}
